Test tests =)
RotLenin/s-chistogo-lista pull request #2
Opened 2024-01-19 13:28 UTC by RotLenin

Commit to test how test works =)

2024-01-19 16:15 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- похоже на макет
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев «Можно лучше» и «Отлично»**

- https://disk.yandex.ru/i/fKfRsok-zxhELw
  -  после исправлений названий шрифта нужно так же будет поправить эти названия в файлах стилей
  -  Нужно проверить корректный альтернативный шрифт **(тип засечек для выбора шрифта браузера без засечек по-умолчанию значение sans-serif и для шрифта с засечками тип serif)** для каждого значения font-family в проекте, кроме файла подключения шрифтов, где это св-во задаёт только название подключаемого шрифта
    - https://doka.guide/css/font-family


_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +  <title>Practicum project 2</title>
---

**Можно лучше:**

Желательно назвать страницу в соответствии с её содержимым

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +<head>
https://disk.yandex.ru/i/ywekHM2O0bccWw Не добавлен тег meta[name=viewport], сайт будет некорректно отображаться при различных ширинах и на различных устройствах. Пример должен быть в уроках или/и в начальном наборе для работы.


 - https://developer.mozilla.org/ru/docs/Glossary/Viewport

2024-01-19 16:15 UTC, Avaakum commented on fonts/fonts.css
> +    font-family: 'Inter bold';
Используйте одно имя для всех шрифтов одного семейства, например `Inter`. Таким образом, если задать шрифт сразу блоку или всей странице, то выбираться конкретный будет только при уточнении параметров, `font-weight`, `font-style`, что очень удобно, и так не нужно для каждого текстового элемента писать определенное имя конкретного шрифта. 

- https://developer.mozilla.org/ru/docs/Web/CSS/font-weight 
- https://developer.mozilla.org/ru/docs/Web/CSS/font-style

2024-01-19 16:15 UTC, Avaakum commented on fonts/fonts.css
> +    font-family: 'Inter regular';
Используйте одно имя для всех шрифтов одного семейства, например `Inter`.

2024-01-19 16:15 UTC, Avaakum commented on fonts/fonts.css
> +    font-family: 'EB Garamond medium';
Используйте одно имя для всех шрифтов одного семейства, например `EB Garamond`. Таким образом, если задать шрифт сразу блоку или всей странице, то выбираться конкретный будет только при уточнении параметров, `font-weight`, `font-style`, что очень удобно, и так не нужно для каждого текстового элемента писать определенное имя конкретного шрифта. 

- https://developer.mozilla.org/ru/docs/Web/CSS/font-weight 
- https://developer.mozilla.org/ru/docs/Web/CSS/font-style

2024-01-19 16:15 UTC, Avaakum commented on fonts/fonts.css
> +    font-family: 'EB Garamond regular';
Используйте одно имя для всех шрифтов одного семейства, например `EB Garamond`.

2024-01-19 16:15 UTC, Avaakum commented on fonts/fonts.css
> +    url("ebgaramondmedium.woff") format('woff'),
---

**Отлично:**

правильный порядок подключения файлов, от самого современного к самому старому формату

2024-01-19 16:15 UTC, Avaakum commented on styles/header.css
> +    width: 79px;
---

**Можно лучше:**

Присвойте размеры картинке, а ссылка в любом случае будет размером с картинку

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +    height: 100vh;
Лишний стиль, или при желании можно использовать min-height, сейчас html сильно ниже всей страницы https://disk.yandex.ru/i/Vmzi13s5DwZ4aA

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +html {
Нужно исправить:


Используйте селектор :root для определения переменных умолчанию, при таком селекторе они будут работать почти везде, даже если в тег  `<head>` добавить тег `<style>`

---

**Можно лучше:**



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +    --gray : #f5f5f5;
---

**Отлично:**

Очень круто, что уже умеете использовать нативные css переменные

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +    width: 100%;
Мы не присваиваем никаких стилей тегам, которые находятся выше по иерархии чем тег body. Присвойте стили для тега body

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +    background-color: var(--black);
У body как раз будет серый цвет, а чёрный нужно присвоить отдельно нужным секциям

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +    <a class='header__logo-link' href='#0'>
Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы.

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <li class='nav__item'>Главная</li>
Внутри должна быть ссылка с атрибутом href. Для ссылок можно добавлять разные классы, что бы присваивать те или иные стили


---

- У всех ссылок на странице, кроме логотипа в хедере(там тег ссылки нужен только для улучшения семантики, без перехода по ссылке) должен быть атрибут href, или они будут неактивны. Если адресов ссылок пока нет, то можно поставить в значение например ` #0 `

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <div class='content-section__title-wrapper'>
Это должен быть h2 по структуре заголовков


---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <h2 class='content-section__title m0'>Почему чистый лист</h2>
Используйте теги span для стилизации внутри заголовка, это один заголовок по смыслу

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <h2 class='content-section__title m0 text-left'> — такой cтрашный?</h2>
Используйте теги span для стилизации внутри заголовка, это один заголовок по смыслу

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <h3 class='content-section__subtitle'>Сам по себе чистый лист, конечно, не страшный. Боимся мы чаще всего объёма работы, которую предстоит сделать. Усилия, той точки, которую нужно преодолеть,
Это не заголовок, используйте тег p

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <li class='how-to__list-item'><strong>Неуверенность в результате.</strong>И в том, что его вообще можно достичь. Ведь как можно быть уверенным, что проводишь всю работу не впустую? Что доведё
Тег strong(как теги b и i) практически не используются в современной вёрстке. Мы стилизуем элементы через CSS, используйте тег span и изменение веса шрифта

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <ul class='how-to__list'>
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <div class='content-section__title-wrapper'>
Это должен быть h2

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <h2 class='content-section__title m0'>Как всё-таки начать</h2>
Используйте тег span

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <h2 class='content-section__title m0 text-left'>что-то делать</h2>
Используйте тег span

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <h3 class='content-section__subtitle'>Чаще всего страх чистого листа появляется не из-за чего-то одного, а из-за совокупности нескольких факторов. Вот что может помочь:</h3>
Это не заголовок, используйте тег p

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +          <article class='card card_gray'>
---

**Отлично:**

Отличная семантика и структура

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +              <span class='card__avatar-author'>Алексей Поляринов</span>
---

**Можно лучше:**

Тег span мы больше используем для стилизации внутри текста или для небольшого декоративного текста, как одно слово. Тут уже хорошо подойдёт тег p

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +    <p class='footer__copy'>© VЁRSTKA</p>
---

**Можно лучше:**

Это как раз декоративный текст, можно использовать span

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +        <time class='intro__date' datetime='2022-06-05'>05.06.2022 г.</time>
---

**Отлично:**

Отличная семантика

2024-01-19 16:15 UTC, Avaakum commented on index.html
> +      <p class='content-section__p m0'>Прокрастинировать перед тем, как начать что-то делать (особенно что-то новое) — нормальная реакция мозга. Разберёмся, почему это происходит.</p>
Параграфы нужно объединить в общий контейнер по смыслу "текст". А так же отступ между параграфами можно задать через flex gap. Параграфов может быть любое количество и отступы должны работать без доп. классов. Различающиеся классы для параграфов нужно удалить

2024-01-19 16:15 UTC, Avaakum commented on styles/style.css
> +@import "reset.css";
---

**Можно лучше:**

Круто, что умеете использовать импорты и разделять код на части. Желательно использовать для файловой системы общеизвестные техники и технологии, что бы сторонним разработчикам было проще разобраться в коде. Например, для подобных целей есть файловая система nested БЭМ. Соответственно и классы так же должны быть по БЭМ. Пожалуйста, в будущих проектах пока добавляйте большую часть стилей в style.css(кроме глобальных стилей и подключения шрифтов).

2024-01-21 07:22 UTC, RotLenin commented on fonts/fonts.css
> +    font-family: 'Inter bold';
Интересно, с точностью наоборот сделал ) Чтобы не писать font-weight и font-style влил их в название шрифтов. ну ладно переделаем.

Думаю в этом проекте мой вариант даже оптимальнее, а вот в большом точно вариант из review

2024-01-21 07:26 UTC, RotLenin commented on styles/style.css
> +    height: 100vh;
Тут такой нюанс, хотел сделать по взрослому с html на всю страницу и прокруткой body, но там идут проблемы из за большого Скролла у body - летит верстка. Так что отказался от этой идеи. Окей поправим

2024-01-22 02:16 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_


- при отправке работы на проверку, скидывайте пожалуйста только ссылку на пулл реквест
- https://disk.yandex.ru/i/qdt-U8jwlTU94w Eb-garamond - это шрифт с засечками, для всех св-в font-family с этим шрифтом нужна альтернатива шрифта serif


---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-01-22 11:27 UTC, merged